name: Docker for Windows

on:
  push: {}
  workflow_dispatch:
    inputs: {}

jobs:
  docker:
    runs-on: windows-2019
    continue-on-error: true
    steps:
      - name: Show $PATH
        run: |
          cd R-3.6.2
          docker build .
