name: Test
on: push

jobs:
  container-job:
    runs-on: windows-latest
    steps:
      - name: Pull some image
        run: |
          docker pull mcr.microsoft.com/windows/servercore
          docker run mcr.microsoft.com/windows/servercore echo "Hello World!"
