name: Docker for Windows

on:
  push: {}
  workflow_dispatch:
    inputs: {}

jobs:
  docker:
    runs-on: windows-2019
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test docker build
        run: |
          cd R-3.6.3
          docker build .
