name: Docker for Windows

on:
  push: {}
  workflow_dispatch:
    inputs: {}

jobs:
  docker:
    runs-on: windows-2019
    continue-on-error: true
    steps:
      - name: Show $PATH
        run: |
          docker pull nuest/rocker-win
          docker run --rm -it nuest/rocker-win Rscript.exe -e "1+1"
